"""Coding agent workflow that emits traces to AMP with auto-evaluation.

Uses WolfpackObserver for telemetry. Scores are auto-generated by the AMP
ingestion pipeline — no manual score publishing needed.

Run with AMP running:
    uv run python examples/18_coding_agent/02_amp_coding_workflow.py
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
import time
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from wolfpack.coding import CodingToolkit, GitRepository, Workspace
from wolfpack.mesh import MeshIdentity
from wolfpack.observer.client import WolfpackObserver

AMP_URL = os.environ.get("WOLFPACK_AMP_URL", "http://localhost:8000")
API_KEY = os.environ.get("WOLFPACK_AMP_API_KEY", "pk-wp-dev:dev-secret")


def _api(path: str, method: str = "GET", body: dict | None = None) -> dict:
    url = f"{AMP_URL}/api/public{path}"
    data = json.dumps(body).encode() if body else None
    req = urllib.request.Request(url, data=data, method=method, headers={"Content-Type": "application/json", "X-API-Key": API_KEY})
    with urllib.request.urlopen(req, timeout=10) as resp:
        return json.loads(resp.read())


def _wait_for_trace(trace_id: str, timeout: float = 10.0) -> dict | None:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            return _api(f"/traces/{trace_id}")
        except urllib.error.HTTPError as exc:
            if exc.code == 404:
                time.sleep(0.5)
                continue
            raise
    return None


def _find_registration() -> MeshIdentity:
    catalog = _api("/mesh/catalog")
    for env in catalog.get("environments", []):
        if env["slug"] == "development":
            for reg in env.get("registrations", []):
                if reg["definition_key"] == "weather-operations":
                    return MeshIdentity(
                        environment_id=env["id"], environment_slug=env["slug"],
                        registration_id=reg["id"], definition_key=reg["definition_key"],
                        definition_version=reg["definition_version"],
                    )
    raise RuntimeError("weather-operations not found. Run amp seed-demo.")


def _git(root: Path, *args: str) -> None:
    subprocess.run(["git", *args], cwd=root, check=True, capture_output=True)


def main() -> None:
    print(f"AMP endpoint: {AMP_URL}")
    identity = _find_registration()
    print(f"  Registration: {identity.definition_key} v{identity.definition_version}")

    observer = WolfpackObserver(base_url=AMP_URL, api_key=API_KEY, deployment=identity, max_batch=100, redact_pii=False)

    with tempfile.TemporaryDirectory() as tmpdir:
        root = Path(tmpdir)
        _git(root, "init", "-b", "main")
        _git(root, "config", "user.email", "agent@wolfpack.example")
        _git(root, "config", "user.name", "Coding Agent")
        (root / "message.txt").write_text("before\n", encoding="utf-8")
        _git(root, "add", "message.txt")
        _git(root, "commit", "-m", "initial")

        workspace = Workspace(root)

        # --- Trace: coding agent workflow ---
        trace = observer.start_trace("coding_agent_workflow")

        # 1. Read file
        span = observer.start_span("tool", "workspace_read")
        content = workspace.read_file("message.txt")
        observer.end_span(span, input={"file": "message.txt"}, output={"content": content.content})

        # 2. Apply patch
        span = observer.start_span("tool", "patch_apply")
        result = workspace.apply_patch("""--- a/message.txt\n+++ b/message.txt\n@@ -1 +1 @@\n-before\n+after\n""")
        observer.end_span(span, input={"patch": "change 'before' to 'after'"}, output={"changed_files": list(result.changed_files)})

        # 3. Run test (verify content)
        span = observer.start_span("tool", "test_run")
        git = GitRepository(workspace)
        status = git.status()
        test_passed = status.changed == ("message.txt",)
        observer.end_span(span, input={"command": "git status"}, output={"passed": test_passed, "changed": status.changed})

        observer.end_trace(trace, input={"action": "read, patch, test"}, output={"test_passed": test_passed})

        print(f"Trace ID: {trace['id']}")
        observer.flush()
        print("Waiting for trace ingestion...")

        time.sleep(1)
        data = _wait_for_trace(trace["id"])
        if data:
            print(f"Trace confirmed with {len(data.get('observations', []))} observations")
        else:
            print("ERROR: trace not found")

        # Verify auto-evaluated scores
        scores = _api(f"/traces/{trace['id']}")["scores"]
        print(f"Auto-evaluated scores: {len(scores)}")
        for s in scores:
            print(f"  {s['name']} = {s['value']} ({s['source']})")

        print("\nDone. Traces available in AMP dashboard.")


if __name__ == "__main__":
    main()