{{- if .Values.ingress.enabled -}}
{{- $fullName := include "wolfpack-control-plane.fullname" . -}}
{{- $frontendName := include "wolfpack-control-plane.frontendName" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "wolfpack-control-plane.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $frontendName }}
                port:
                  number: {{ .Values.frontend.service.port }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecretName | default "wildcard-tls" }}
  {{- end }}
{{- end }}
