"""Personal assistant workflow that emits traces to AMP with auto-evaluation.

Demonstrates scoped memory, reminder scheduling, and external action approval.
Scores are auto-generated by the AMP ingestion pipeline — no manual publishing.

Run with AMP running:
    uv run python examples/17_personal_agent/03_amp_personal_assistant.py
"""

from __future__ import annotations

import json
import os
import sys
import time
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from wolfpack.mesh import MeshIdentity
from wolfpack.observer.client import WolfpackObserver
from wolfpack.personal import ActionPolicy, ExternalActionManager, ReminderService
from wolfpack.schedules import ScheduleTask

AMP_URL = os.environ.get("WOLFPACK_AMP_URL", "http://localhost:8000")
API_KEY = os.environ.get("WOLFPACK_AMP_API_KEY", "pk-wp-dev:dev-secret")


def _api(path: str, method: str = "GET", body: dict | None = None) -> dict:
    url = f"{AMP_URL}/api/public{path}"
    data = json.dumps(body).encode() if body else None
    req = urllib.request.Request(url, data=data, method=method, headers={"Content-Type": "application/json", "X-API-Key": API_KEY})
    with urllib.request.urlopen(req, timeout=10) as resp:
        return json.loads(resp.read())


def _find_registration() -> MeshIdentity:
    catalog = _api("/mesh/catalog")
    for env in catalog.get("environments", []):
        if env["slug"] == "development":
            for reg in env.get("registrations", []):
                if reg["definition_key"] == "weather-operations":
                    return MeshIdentity(
                        environment_id=env["id"], environment_slug=env["slug"],
                        registration_id=reg["id"], definition_key=reg["definition_key"],
                        definition_version=reg["definition_version"],
                    )
    raise RuntimeError("weather-operations not found. Run amp seed-demo.")


class FakeScheduleClient:
    def schedule_task(self, request):
        return ScheduleTask(id="reminder-1", status="active", **request.model_dump())


def main() -> None:
    print(f"AMP endpoint: {AMP_URL}")
    identity = _find_registration()
    print(f"  Registration: {identity.definition_key} v{identity.definition_version}")

    observer = WolfpackObserver(base_url=AMP_URL, api_key=API_KEY, deployment=identity, max_batch=100, redact_pii=False)

    trace = observer.start_trace("personal_assistant_workflow")

    # 1. Reminder scheduling
    span = observer.start_span("tool", "create_reminder")
    reminder = ReminderService(FakeScheduleClient()).create(
        "Stretch", "0 10 * * 1-5", "Take a short stretch break", timezone="America/Sao_Paulo",
    )
    observer.end_span(span, input={"message": "Take a short stretch break", "schedule": "0 10 * * 1-5"}, output={"schedule_id": reminder.schedule_id, "status": reminder.status})

    # 2. External action with approval
    span = observer.start_span("tool", "draft_action")
    actions = ExternalActionManager(ActionPolicy(allowed_actions=frozenset({"email.send"})))
    draft = actions.draft("email.send", "alex@example.test", {"subject": "Weekly plan"})
    observer.end_span(span, input={"action": "email.send"}, output={"id": draft.id, "status": draft.status})

    span = observer.start_span("tool", "approve_action")
    actions.approve(draft.id, note="Reviewed by Alex")
    observer.end_span(span, input={"action_id": draft.id}, output={"note": "Reviewed by Alex"})

    span = observer.start_span("tool", "execute_action")
    completed = actions.execute(draft.id, lambda action: {"delivered": False, "target": action.target})
    observer.end_span(span, input={"action_id": draft.id}, output={"status": completed.status, "delivered": completed.result.get("delivered")})

    observer.end_trace(trace, input={"workflow": "reminder + external action"}, output={"reminder": reminder.schedule_id, "action_status": completed.status})

    print(f"Trace ID: {trace['id']}")
    observer.flush()
    print("Waiting for trace ingestion...")

    time.sleep(1)
    try:
        data = _api(f"/traces/{trace['id']}")
        print(f"Trace confirmed with {len(data.get('observations', []))} observations")
        scores = data.get("scores", [])
        print(f"Auto-evaluated scores: {len(scores)}")
        for s in scores:
            print(f"  {s['name']} = {s['value']} ({s['source']})")
    except Exception as e:
        print(f"Warning: trace verification failed: {e}")

    print("\nDone. Traces available in AMP dashboard.")


if __name__ == "__main__":
    main()