"""persist currency-aware costs and durable execution trace links"""

from alembic import op
import sqlalchemy as sa


revision = "0023_cost_attribution_links"
down_revision = "0022_channel_connections"
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    with op.batch_alter_table("traces") as batch:
        batch.alter_column("total_cost", existing_type=sa.Float(), nullable=True, server_default=None)
        batch.add_column(sa.Column("total_cost_currency", sa.String(3), nullable=True))
        batch.add_column(sa.Column("total_cost_source", sa.String(64), nullable=True))
    with op.batch_alter_table("observations") as batch:
        batch.alter_column("cost", existing_type=sa.Float(), nullable=True, server_default=None)
        batch.add_column(sa.Column("cost_currency", sa.String(3), nullable=True))
        batch.add_column(sa.Column("cost_source", sa.String(64), nullable=True))
    # Pre-attribution zeroes were generated by the old column defaults, not measured costs.
    op.execute("UPDATE traces SET total_cost = NULL WHERE total_cost = 0")
    op.execute("UPDATE observations SET cost = NULL WHERE cost = 0")
    if "trace_id" not in {column["name"] for column in inspector.get_columns("scheduled_task_runs")}:
        op.add_column("scheduled_task_runs", sa.Column("trace_id", sa.String(64), nullable=True))
        op.create_index("ix_scheduled_task_runs_trace", "scheduled_task_runs", ["trace_id"])
    delivery_columns = {column["name"] for column in inspector.get_columns("channel_deliveries")}
    if "chat_run_id" not in delivery_columns:
        op.add_column("channel_deliveries", sa.Column("chat_run_id", sa.String(32), nullable=True))
        op.create_foreign_key("fk_channel_deliveries_chat_run", "channel_deliveries", "chat_runs", ["chat_run_id"], ["id"])
    if "trace_id" not in delivery_columns:
        op.add_column("channel_deliveries", sa.Column("trace_id", sa.String(64), nullable=True))
        op.create_index("ix_channel_deliveries_trace", "channel_deliveries", ["trace_id"])


def downgrade():
    op.drop_index("ix_channel_deliveries_trace", table_name="channel_deliveries")
    op.drop_constraint("fk_channel_deliveries_chat_run", "channel_deliveries", type_="foreignkey")
    op.drop_column("channel_deliveries", "trace_id")
    op.drop_column("channel_deliveries", "chat_run_id")
    op.drop_index("ix_scheduled_task_runs_trace", table_name="scheduled_task_runs")
    op.drop_column("scheduled_task_runs", "trace_id")
    with op.batch_alter_table("observations") as batch:
        batch.drop_column("cost_source")
        batch.drop_column("cost_currency")
        batch.alter_column("cost", existing_type=sa.Float(), nullable=False, server_default="0.0")
    with op.batch_alter_table("traces") as batch:
        batch.drop_column("total_cost_source")
        batch.drop_column("total_cost_currency")
        batch.alter_column("total_cost", existing_type=sa.Float(), nullable=False, server_default="0.0")
